### ISSUE TITLE
Potential resource leak

### ISSUE THREAD

**Issue by seppeljordan** [python-injector/injector#212]
Hi, I might have discovered a resource leak with `injector` and wanted to present my case here.

Consider the following program:

```python
import injector
from time import sleep


class Injector(injector.Injector):
    def __del__(self) -> None:
        print("Finalized", self)


class X:
    def __del__(self) -> None:
        print("Finalized", self)


def f():
    print('start f')
    i = Injector()
    x = i.get(X)
    sleep(1)
    print('end f')


f()
f()
f()
f()
```

There is a function `f` that constructs a new `Injector` instance `i`. `i` is then used to create an instance of `X`. After the execution of `f` finishes there are no more obvious references to `x` or `i` and I would expect them to be garbage collected. The `sleep` instruction is used to give the garbage collector a chance to do its magic.

When I run the program on my system the following output is produced:
```
$ python testcase.py
start f
end f
Finalized <__main__.X object at 0x7fb0682b64a0>
start f
end f
Finalized <__main__.X object at 0x7fb068116500>
start f
end f
Finalized <__main__.X object at 0x7fb068116b00>
start f
end f
Finalized <__main__.X object at 0x7fb068116e90>
Finalized <__main__.Injector object at 0x7fb0682b64a0>
Finalized <__main__.Injector object at 0x7fb068116500>
Finalized <__main__.Injector object at 0x7fb068116b00>
Finalized <__main__.Injector object at 0x7fb0684cffd0>
```

This output suggests that the `Injector` instances created inside of `f` are only finalized right before the main program exits. This looks to me like a resource leak. So now my question: Am I using `Injector` wrong or is this a "proper" bug?

Cheers

EDIT:
```
$ python --version
Python 3.10.9
```

**Comment by tobni** [comment]
I think it would make more sense to use `gc.collect()` instead of `time.sleep`?

But even with this change, it does indeed seem like `Injector` instances are too complicated for the GC to collect at any other generation than 2.

It does collect the injector when it leaves scope and generation 2 of GC is ran, though. The reason for this is most likely the circular references between `Binder` and `Injector` instances. The python GC is capable of dealing with this though, it just wont do it immediately.

I would argue that what you have observed depends on how many iterations of the GC will be executed in any given program.

**Comment by jstasiak** [comment]
Hey, so this is a bit of a funny behavior connected to how Python's garbage collector works. Basically you need to keep generating garbage (with cycles – it's implied everywhere in this comment) for the Python GC to do its thing (see how it's documented here: https://docs.python.org/3/library/gc.html#gc.set_threshold; I can't remember what PyPy does here but CPython works like that).

If you don't generate enough garbage the GC will never run until the interpreter shutdown.

Append this code to your example and it demonstrates what I mean:

```

def stats():
    return [
        len([o for o in gc.get_objects(generation) if isinstance(o, Injector)])
        for generation in [0, 1, 2]
    ]


print(f'Injectors in each generation: {stats()}')
print(f'gc.get_stats(): {gc.get_stats()}')


def generate_garbage():
    thing = {}
    thing['self'] = thing


iterations = 0

while stats() == [3, 1, 0]:
    iterations += 1
    generate_garbage()

print(f'Something was collected after {iterations} pieces of garbage were generated. Quitting')
```

The output (I'm running CPython 3.10.9 but it probably doesn't matter):

```
start f
end f
Finalized <__main__.X object at 0x1045430d0>
start f
end f
Finalized <__main__.X object at 0x10455d660>
start f
end f
Finalized <__main__.X object at 0x104a8b8e0>
start f
end f
Finalized <__main__.X object at 0x104a8b2e0>
Injectors in each generation: [3, 1, 0]
gc.get_stats(): [{'collections': 26, 'collected': 69, 'uncollectable': 0}, {'collections': 2, 'collected': 0, 'uncollectable': 0}, {'collections': 0, 'collected': 0, 'uncollectable': 0}]
Finalized <__main__.Injector object at 0x1045430d0>
Finalized <__main__.Injector object at 0x10455d660>
Finalized <__main__.Injector object at 0x104a8b8e0>
Something was collected after 674 pieces of garbage were generated. Quitting
Finalized <__main__.Injector object at 0x104543fd0>
```

See how three of the instances were collected after we generated 674 pieces of garbage with cycles (important)? 674 + 26 = 700 which is meaningful because 700 is the default `threshold0` value in my environment (`gc.get_threshold()` shows that). 

If we keep generating garbage the fourth instance will be collected too. 

So not quite related to generation 2 @tobni, but this

> I would argue that what you have observed depends on how many iterations of the GC will be executed in any given program.

is spot on (no only the GC needs to actually run at least once in the first place /it only does so when there's garbage being generated/ but it may need to run several times if the objects you're waiting to be finalized are in generation 1 or 2).
